
                    apiVersion: apps/v1
                    kind: Deployment
                    metadata:
                      name: test-deployment
                      labels:
                        app: test
                    spec:
                      revisionHistoryLimit: 2
                      replicas: 3
                      selector:
                        matchLabels:
                          app: test
                      template:
                        metadata:
                          labels:
                            app: test
                        spec:
                          containers:
                          - name: test-container
                            image: sb8citizen/wartoimg:0.58
                            ports:
                            - containerPort: 8080
                    