
                    apiVersion: v1
                    kind: Service
                    metadata:
                      name: test-service
                    spec:
                      type: NodePort
                      selector:
                        app: test
                      ports:
                      - protocol: TCP
                        port: 80
                        targetPort: 8080
                        nodePort: 30007
                    